---
- name: Destroy ChangeDetection.io container
  hosts: all

  vars:
    pod_name: "changedetectionio"
    host_port: 12586
    
  tasks:
    - name: Remove firewall configuration
      ansible.posix.firewalld:
        zone: internal
        port: "{{ host_port }}/tcp"
        permanent: true
        state: enabled
      become: yes

    - name: Remove Systemd service
      import_tasks: ../../common/destroy_remove_systemd_service.yml
      vars:
        service_name: "pod-{{ pod_name }}"

    - name: Remove pod
      containers.podman.podman_pod:
        name: "{{ pod_name }}"
        state: absent

    - name: "Finished" 
      ansible.builtin.debug:
        msg: "Content of `{{ ansible_env.HOME }}/containers/{{ pod_name }}` has been preserved."