---
- name: Destroy Serpbear container
  hosts: all

  vars:
    container_name: "serpbear"
    host_port: 12585
    
  tasks:
    - name: Remove firewall configuration
      ansible.posix.firewalld:
        zone: internal
        port: "{{ host_port }}/tcp"
        permanent: true
        state: enabled
      become: yes

    - name: Remove Systemd service
      import_tasks: ../../common/destroy_remove_systemd_service.yml
      vars:
        service_name: "container-{{ container_name }}"

    - name: Remove container
      containers.podman.podman_container:
        name: "{{ container_name }}"
        state: absent

    - name: "Finished" 
      ansible.builtin.debug:
        msg: "Content of `{{ ansible_env.HOME }}/containers/{{ container_name }}` has been preserved."